<a href="https://colab.research.google.com/github/jcmachicao/uc_curso_modelamientopredictivo/blob/master/modpred_00A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Cuaderno 00
# **Curso Modelamiento Predictivo**
---
* **Introducción a Bases de Datos Numpy y Pandas**
* Autor: José Carlos Machicao
* Licencia: [GestioDinámica](http://www.gestiodinamica.com) 2020

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Una sola celda

In [3]:
cel_np = np.array([3])
cel_np

array([3])

In [5]:
cel_pd = pd.DataFrame([3])
cel_pd

0
0  3

Varias celdas

In [8]:
colec_np = np.array([3, 2, 4, 8, 5])
colec_np

array([3, 2, 4, 8, 5])

In [9]:
colec_pd = pd.DataFrame([3, 2, 4, 8, 5])
print(colec_pd)

   0
0  3
1  2
2  4
3  8
4  5


Una tabla más completa

In [13]:
lista_de_filas = [ [2, 3, 4], [4, 7, 5] ]

In [14]:
tabla_np = np.array(lista_de_filas)
tabla_np

array([[2, 3, 4],
       [4, 7, 5]])

In [15]:
tabla_df = pd.DataFrame(lista_de_filas)
tabla_df

0  1  2
0  2  3  4
1  4  7  5